### PR TITLE
Junxian Yu - Assignment Week 9: Added record_game_data and integrated turtle_race.py

### PR DESCRIPTION
**Pull request by yujunxian**
This PR adds the record_game_data function to save game data to a CSV file.

### CODE REVIEW

**Comment by yujunxian** [comment]
Junxian Yu

#Assignment Week 9

This Pull Request includes:
- Added the `record_game_data` function to save user bets and winning colors.
- Integrated the function with `turtle_race.py`.
- Tested the game for multiple rounds and recorded data in `game_data.csv`.

**Review by yujunxian — COMMENTED** [review]
- Added the `record_game_data` function to save user bets and winning colors.
- Integrated the function with `turtle_race.py`.
- Data in `game_data.csv`.

**Comment by yujunxian** [comment]
Junxian Yu 

Screenshot of VS Code Terminal.

Screenshot 2024-11-26 at 12 31 57

**Comment by luyaoniu-uw** [comment]
Thanks! Happy holiday!

**Pull request closed without merging**
